touchscreen: heatmap: fix build break of variable length array used
drivers/input/touchscreen/heatmap.c:79:24: error: variable length array used [-Werror,-Wvla]
strength_t temp_buffer[total_bytes];

Bug: 139783401
Test: Use v4l-heatmap-viewer.apk(provided in bug) to check touch heatmap is workable.

Change-Id: I640a711a4065f2909e4aa0738eae2b1e36c817d5
Signed-off-by: davidycchen <davidycchen@google.com>
(cherry picked from commit 752bb006b9865a0268b5dd3c677d03c0873f8e84)